/*
 * This source file was generated by the Gradle 'init' task
 */
package arraymirror;

public class App {
    int arr[][];
    int new_arr[][];

    public void input(int row,int col) {
        arr = new int[row][col];
    }
    

    public static void main(String[] args) {
        // Write a code to print a number from 2 to 15 using the for loop
            // For loop from 2 to 15
            for (int i = 2; i <= 15; i++) {
                System.out.println(i); // Print each number
            }
        }
    }
    
